### ISSUE TITLE
TypeError: Fle is not a function

### ISSUE THREAD

**Issue by SmokelessLlama** [Maker-Management-Platform/mmp-ui#90]
I get the following error with I click on any file that is not an image, when clicking the names under the files, and when clicking the file menu and "details". 

```
Unexpected Application Error!
Fle is not a function
TypeError: Fle is not a function
    at zle (http://192.168.1.13:8081/assets/index-dc269569.js:3852:26106)
    at GM (http://192.168.1.13:8081/assets/index-dc269569.js:38:19538)
    at kO (http://192.168.1.13:8081/assets/index-dc269569.js:40:44055)
    at IO (http://192.168.1.13:8081/assets/index-dc269569.js:40:39787)
    at a6 (http://192.168.1.13:8081/assets/index-dc269569.js:40:39715)
    at wy (http://192.168.1.13:8081/assets/index-dc269569.js:40:39568)
    at EE (http://192.168.1.13:8081/assets/index-dc269569.js:40:35933)
    at TR (http://192.168.1.13:8081/assets/index-dc269569.js:40:36737)
    at Ql (http://192.168.1.13:8081/assets/index-dc269569.js:38:3279)
    at http://192.168.1.13:8081/assets/index-dc269569.js:40:34263
```

there is an fle function:

```
function fle(t, e, n) {
    return e && EI(t.prototype, e),
    n && EI(t, n),
    Object.defineProperty(t, "prototype", {
        writable: !1
    }),
    t
}
```
maybe a typo somewhere?

I've disabled all extensions and cleared the cache.
happens on any browser I try. Running mmp in docker in a proxmox ct. Not sure what other info you need.

**Comment by EduardoOliveira** [comment]
Hi, what browser are you using? A recent chrome, firefox or edge?
I was unable to reproduce, but I fixed another problem in the part of the code, could you please try this image https://github.com/Maker-Management-Platform/mmp-ui/pkgs/container/mmp-ui/168669729?tag=90-typeerror-fle-is-not-a-function ? Se if it solves your issue?

**Comment by jviehmeyer** [comment]
I'm getting the same error even with the modification of the 90-typeerror-file... 

I'm using chrome, confirmed to be an issue in Edge as well. 

```Unexpected Application Error!
Fle is not a function
TypeError: Fle is not a function
    at zle (http://localhost:8081/assets/index-dc269569.js:3852:26106)
    at GM (http://localhost:8081/assets/index-dc269569.js:38:19538)
    at kO (http://localhost:8081/assets/index-dc269569.js:40:44055)
    at IO (http://localhost:8081/assets/index-dc269569.js:40:39787)
    at a6 (http://localhost:8081/assets/index-dc269569.js:40:39715)
    at wy (http://localhost:8081/assets/index-dc269569.js:40:39568)
    at EE (http://localhost:8081/assets/index-dc269569.js:40:35933)
    at TR (http://localhost:8081/assets/index-dc269569.js:40:36737)
    at Ql (http://localhost:8081/assets/index-dc269569.js:38:3279)
    at http://localhost:8081/assets/index-dc269569.js:40:34263```

Exact repro steps: 
1.) Navigate to Project. 
2.) Pick a non-image, print file, click download details

**Comment by EduardoOliveira** [comment]
Found the culprit...
![image](https://github.com/Maker-Management-Platform/mmp-ui/assets/1675917/3032157f-aeae-463e-90e2-7eebe4af6dd5)

I'm gonna temporarily remove dayJS, it will make dates ugly but will allow it to function until there is time for a proper fix

**Comment by EduardoOliveira** [comment]
Pushing a real fix
There will be another release today...
